Repository AY2324S2-CS2113-T13-4/tp, pull requests merged in 2024-03, with the labels that each got.

#40 Add more error checking conditions
  src/main/java/supertracker/command/DeleteCommand.java
  src/main/java/supertracker/command/UpdateCommand.java
  src/main/java/supertracker/parser/Parser.java
  src/main/java/supertracker/ui/ErrorMessage.java
  src/main/java/supertracker/ui/Ui.java
Labels: priority.High

#48 Refactor code
  src/main/java/supertracker/SuperTracker.java
  src/main/java/supertracker/parser/Parser.java
  src/main/java/supertracker/ui/Ui.java
  src/test/java/supertracker/parser/ParserTest.java
Labels: severity.Low

#56 Add sort feature
  src/main/java/supertracker/command/FindCommand.java
  src/main/java/supertracker/command/ListCommand.java
  src/main/java/supertracker/item/Inventory.java
  src/main/java/supertracker/item/Item.java
  src/main/java/supertracker/parser/Parser.java
  src/main/java/supertracker/ui/Ui.java
Labels: priority.High

#64 Update DG
  docs/DeveloperGuide.md
  docs/uml-diagrams/Parser.puml
  docs/uml-diagrams/ParserClass.png
  docs/uml-diagrams/ParserSequence.png
Labels: priority.Medium

#65 Add input parser support for multiple character parameter flags
  src/main/java/supertracker/parser/Parser.java
Labels: priority.High
